### ISSUE TITLE
History Crop vs. History Cutout

### ISSUE THREAD

**Issue by oezyurty** [ratschlab/ncl#3]
Hi, 

First of all, thanks for the great work in your paper, your approach is quite novel and interesting! 

I am mostly interested in data augmentations you applied in time series data (which are rare to find in other papers). Hence, I would like to raise a couple of questions regarding history crop and cutout (and their sequential combination). I really appreciate your answers in advance. 

- Practically, what is the difference between history cutout and crop? (other than one is fixed-length interval and the other one is left-sided). 
- For history crop, what is the purpose of *padding_mask* and *padding_size*? To my understanding, it will help you skip first N timesteps that you pre-padded for shorter sequences. However, if history cutout is applied before (according to your gin configuration files), then you are skipping extra timesteps with the *size* you masked out in history cutout. What is the purpose for this? If you masked out a time portion from the end of sequence, you are extra penalizing the sequence by further cropping extra timesteps from the beginning (because of the computation of *boxes_start*).

If my understanding is wrong, I would be happy to hear your further explanations as well. Thanks in advance!

**Comment by hugoych** [comment]
Hi, 

Concerning your first question, practically history cutout and crop are very similar indeed! As you said they are both crops but one has the constraint of being left-sided (crop) while the other is fixed-sized (cutout) while not impairing the last state.

For your second point, I just checked the code again and you're absolutely right! This is an error from my side. Thus, using crop after cutout leads to preserving a smaller history (~min_history*(1 - TCO_SIZE/48)), which in our case corresponds to a minimum history of 41.6% rather than 50%. 

Luckily this has no impact on performance as we actually didn't find any statistically significant improvement/decrease in performance when varying history from 25% to 75% when used in conjunction with all the other augmentations. 

Thanks a lot for spotting this! I'll change the code to catch the first non_padding value rather than counting padding values and push it in the upcoming days.

**Comment by oezyurty** [comment]
Hi, 

Thank you so much for the quick reply! Yes, I think it makes sense to catch first non_padding value instead. 

I will be closing this issue. Good luck with your next projects!
